[tool.poetry]
name = "pybotx-smartapp-rpc"
version = "0.5.0"
description = "eXpress SmartApp JSON-RPC library"
authors = ["Arseniy Zhiltsov <arseniy.zhiltsov@ccsteam.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<3.11"

pybotx = ">=0.32.0,<0.45.0"

pydantic = "^1.8.2"
fastapi = ">=0.70.0,<0.75.0"

[tool.poetry.dev-dependencies]
add-trailing-comma = "^2.2.1"
black = "22.3.0"
isort = "^4.3"
autoflake = "^1.4"
mypy = "0.910"
wemake-python-styleguide = "0.16.1"

pytest = "^7.0.1"
pytest-asyncio = "^0.18.1"
pytest-cov = "^3.0.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
