[tool.poetry]
name = "pybotx-smartapp-rpc"
version = "0.9.0"
description = "eXpress SmartApp JSON-RPC library"
authors = ["Arseniy Zhiltsov <arseniy.zhiltsov@ccsteam.ru>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.8,<3.12"

pydantic = ">=1.6.0,<1.11.0"
pybotx = ">=0.67.0"

[tool.poetry.dev-dependencies]
add-trailing-comma = "^2.2.1"
black = "22.3.0"
isort = "5.10.1"
autoflake = "^1.4"
mypy = "0.910"
wemake-python-styleguide = "0.16.1"

pytest = "^7.0.1"
pytest-asyncio = "^0.18.1"
pytest-cov = "^4.1.0"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
